import promptSync = require("prompt-sync");

const prompt = promptSync();

const countryCodes: { [key: string]: string } = {
    "F": "Afghanistan",
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarctica",
    "AG": "Antigua and Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BQ": "Bonaire, Sint Eustatius and Saba",
    "BA": "Bosnia and Herzegovina",
    "BW": "Botswana",
    "BV": "Bouvet Island",
    "BR": "Brazil",
    "IO": "British Indian Ocean Territory",
    "BN": "Brunei Darussalam",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "CV": "Cabo Verde",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "KY": "Cayman Islands",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CX": "Christmas Island",
    "CC": "Cocos (Keeling) Islands",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": "Congo",
    "CD": "Congo, Democratic Republic of the",
    "CK": "Cook Islands",
    "CR": "Costa Rica",
    "CI": "Côte d\\'Ivoire",
    "HR": "Croatia",
    "CU": "Cuba",
    "CW": "Curaçao",
    "CY": "Cyprus",
    "CZ": "Czechia",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "SZ": "Eswatini",
    "ET": "Ethiopia",
    "FK": "Falkland Islands (Malvinas)",
    "FO": "Faroe Islands",
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GF": "French Guiana",
    "PF": "French Polynesia",
    "TF": "French Southern Territories",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GG": "Guernsey",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Heard Island and McDonald Islands",
    "VA": "Holy See",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IM": "Isle of Man",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "JP": "Japan",
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KP": "North Korea",
    "KR": "South Korea",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Lao",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libya",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexico",
    "FM": "Micronesia",
    "MD": "Moldova",
    "MC": "Monaco",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MS": "Montserrat",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Netherlands",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MK": "North Macedonia",
    "MP": "Northern Mariana Islands",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestine",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PN": "Pitcairn",
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RO": "Romania",
    "RU": "Russia",
    "RW": "Rwanda",
    "RE": "Réunion",
    "BL": "Saint Barthélemy",
    "SH": "Saint Helena",
    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "MF": "Saint Martin (French)",
    "PM": "Saint Pierre and Miquelon",
    "VC": "Saint Vincent and the Grenadines",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome and Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SX": "Sint Maarten (Dutch)",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "GS": "South Georgia and the South Sandwich Islands",
    "SS": "South Sudan",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SJ": "Svalbard and Jan Mayen",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syria",
    "TW": "Taiwan",
    "TJ": "Tajikistan",
    "TZ": "Tanzania",
    "TH": "Thailand",
    "TL": "Timor-Leste",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": "Turks and Caicos Islands",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
    "UM": "United States Minor Outlying Islands",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "VG": "British Virgin Islands",
    "VI": "United States Virgin Islands",
    "WF": "Wallis and Futuna",
    "EH": "Western Sahara",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabw"
};

const adjacentCountries: { [key: string]: string[] } = {
    'AF': ['IR', 'PK', 'TM', 'UZ', 'TJ', 'CN'],
    'AL': ['ME', 'RS', 'MK', 'GR'],
    'DZ': ['TN', 'LY', 'NE', 'ML', 'MR', 'EH', 'MA'],
    'AS': [],
    'AD': ['ES', 'FR'],
    'AO': ['CD', 'CG', 'ZM', 'NA'],
    'AI': [],
    'AQ': [],
    'AG': [],
    'AR': ['CL', 'BO', 'PY', 'UY', 'BR'],
    'AM': ['GE', 'AZ', 'TR', 'IR'],
    'AW': [],
    'AU': ['PG', 'ID'],
    'AT': ['DE', 'CZ', 'SK', 'HU', 'SI', 'IT', 'CH'],
    'AZ': ['AM', 'GE', 'RU', 'IR'],
    'BS': [],
    'BH': ['SA', 'QA'],
    'BD': ['IN', 'MM'],
    'BB': [],
    'BY': ['RU', 'UA', 'PL', 'LT', 'LV'],
    'BE': ['FR', 'DE', 'NL', 'LU'],
    'BZ': ['MX', 'GT'],
    'BJ': ['NE', 'NG', 'TG', 'BF'],
    'BM': [],
    'BT': ['IN', 'CN'],
    'BO': ['AR', 'CL', 'PY', 'BR', 'PE'],
    'BQ': [],
    'BA': ['HR', 'ME', 'RS'],
    'BW': ['NA', 'ZM', 'ZW', 'ZA'],
    'BV': [],
    'BR': ['AR', 'UY', 'PY', 'BO', 'PE', 'CO', 'VE', 'GY', 'SR', 'GF'],
    'IO': [],
    'BN': ['MY'],
    'BG': ['RO', 'RS', 'MK', 'GR', 'TR'],
    'BF': ['ML', 'NE', 'BJ', 'TG', 'GH', 'CI'],
    'BI': ['RW', 'TZ', 'CD'],
    'CV': [],
    'KH': ['VN', 'LA', 'TH'],
    'CM': ['NG', 'TD', 'CF', 'GA', 'GQ'],
    'CA': ['US'],
    'KY': [],
    'CF': ['TD', 'SD', 'SS', 'CD', 'CG', 'CM'],
    'TD': ['LY', 'NE', 'NG', 'CM', 'CF', 'SD'],
    'CL': ['AR', 'BO', 'PE'],
    'CN': ['RU', 'MN', 'KZ', 'IN', 'NP', 'BT', 'LA', 'VN', 'KR', 'PK'],
    'CO': ['PA', 'BR', 'PE', 'VE', 'EC'],
    'KM': [],
    'CG': ['CM', 'CF', 'GA', 'AO'],
    'CD': ['SS', 'CF', 'CG', 'RW', 'TZ', 'BI', 'UG', 'ZM', 'AO'],
    'CK': [],
    'CR': ['NI', 'PA'],
    'CI': ['GH', 'BF', 'ML', 'LR'],
    'HR': ['SI', 'HU', 'RS', 'BA', 'ME'],
    'CU': [],
    'CW': [],
    'CY': [],
    'CZ': ['DE', 'AT', 'SK', 'PL'],
    'DK': ['DE'],
    'DJ': ['ER', 'ET', 'SO'],
    'DM': [],
    'DO': ['HT'],
    'EC': ['CO', 'PE'],
    'EG': ['LY', 'SD', 'IL', 'PS'],
    'SV': ['GT', 'HN'],
    'GQ': ['CM', 'GA'],
    'ER': ['DJ', 'ET', 'SD'],
    'EE': ['LV', 'RU'],
    'SZ': ['ZA', 'MZ'],
    'ET': ['SD', 'SS', 'KE', 'SO', 'DJ', 'ER'],
    'FJ': [],
    'FI': ['SE', 'NO', 'RU'],
    'FR': ['BE', 'LU', 'DE', 'CH', 'IT', 'ES', 'AD', 'MC'],
    'GA': ['GQ', 'CM', 'CG'],
    'GM': ['SN'],
    'GE': ['RU', 'AZ', 'AM', 'TR'],
    'DE': ['DK', 'PL', 'CZ', 'AT', 'CH', 'FR', 'LU', 'BE', 'NL'],
    'GH': ['CI', 'BF', 'TG'],
    'GR': ['AL', 'MK', 'BG', 'TR'],
    'GL': [],
    'GD': [],
    'GU': [],
    'GT': ['MX', 'BZ', 'SV', 'HN'],
    'GN': ['SL', 'LR', 'CI', 'ML', 'SN', 'GW'],
    'GW': ['SN', 'GN'],
    'GY': ['VE', 'BR', 'SR'],
    'HT': ['DO'],
    'HN': ['GT', 'SV', 'NI'],
    'HK': [],
    'HU': ['SK', 'AT', 'SI', 'RS', 'RO', 'UA', 'HR'],
    'IS': [],
    'IN': ['PK', 'CN', 'NP', 'BT', 'BD', 'MM'],
    'ID': ['PG', 'MY'],
    'IR': ['IQ', 'AF', 'PK', 'TM', 'AZ', 'AM', 'TR'],
    'IQ': ['IR', 'SY', 'SA', 'TR', 'JO', 'KW'],
    'IE': ['GB'],
    'IL': ['EG', 'PS', 'JO', 'SY', 'LB'],
    'IT': ['FR', 'CH', 'AT', 'SI', 'SM', 'VA'],
    'JM': [],
    'JP': [],
    'JO': ['IQ', 'SY', 'IL', 'PS', 'SA'],
    'KZ': ['RU', 'CN', 'KG', 'UZ', 'TM'],
    'KE': ['ET', 'SS', 'UG', 'TZ', 'SO'],
    'KG': ['KZ', 'UZ', 'TJ', 'CN'],
    'LA': ['VN', 'KH', 'TH', 'MM', 'CN'],
    'LV': ['LT', 'EE', 'RU', 'BY'],
    'LB': ['SY', 'IL'],
    'LS': ['ZA'],
    'LR': ['GN', 'CI', 'SL'],
    'LY': ['TN', 'DZ', 'NE', 'TD', 'SD', 'EG'],
    'LI': ['CH', 'AT'],
    'LT': ['LV', 'BY', 'PL', 'RU'],
    'LU': ['FR', 'DE', 'BE'],
    'MG': [],
    'MW': ['TZ', 'MZ', 'ZM'],
    'MY': ['TH', 'BN', 'ID'],
    'MV': [],
    'ML': ['SN', 'GN', 'CI', 'BF', 'NE', 'DZ', 'MR'],
    'MT': [],
    'MX': ['US', 'BZ', 'GT'],
    'FM': [],
    'MD': ['RO', 'UA'],
    'MC': ['FR'],
    'MN': ['CN', 'RU'],
    'ME': ['HR', 'RS', 'BA', 'AL', 'XK'],
    'MA': ['DZ', 'EH'],
    'MZ': ['ZW', 'ZA', 'SZ', 'MW', 'TZ'],
    'MM': ['IN', 'BD', 'TH', 'CN', 'LA'],
    'NA': ['ZA', 'BW', 'AO', 'ZM'],
    'NP': ['IN', 'CN'],
    'NL': ['BE', 'DE'],
    'NZ': [],
    'NI': ['HN', 'CR'],
    'NE': ['DZ', 'LY', 'TD', 'NG', 'BF', 'ML'],
    'NG': ['BJ', 'NE', 'TD', 'CM'],
    'NO': ['SE', 'FI', 'RU'],
    'OM': ['YE', 'SA', 'AE'],
    'PK': ['AF', 'IN', 'CN', 'IR'],
    'PA': ['CR', 'CO'],
    'PG': ['ID'],
    'PY': ['BO', 'AR', 'BR'],
    'PE': ['EC', 'CO', 'BR', 'BO', 'CL'],
    'PH': [],
    'PL': ['DE', 'CZ', 'SK', 'UA', 'BY', 'LT', 'RU'],
    'PT': ['ES'],
    'QA': ['SA', 'BH'],
    'RO': ['UA', 'MD', 'HU', 'RS', 'BG'],
    'RU': ['NO', 'FI', 'EE', 'LV', 'LT', 'PL', 'UA', 'BY', 'KZ', 'CN', 'MN', 'KP'],
    'RW': ['BI', 'TZ', 'CD', 'UG'],
    'WS': [],
    'SM': ['IT'],
    'ST': [],
    'SA': ['YE', 'OM', 'AE', 'QA', 'KW', 'IQ', 'JO'],
    'SN': ['GN', 'GW', 'ML', 'MR'],
    'RS': ['HU', 'RO', 'BG', 'MK', 'AL', 'XK', 'ME', 'HR', 'BA'],
    'SC': [],
    'SL': ['GN', 'LR'],
    'SG': [],
    'SK': ['CZ', 'AT', 'HU', 'PL', 'UA'],
    'SI': ['IT', 'AT', 'HU', 'HR'],
    'SB': [],
    'SO': ['ET', 'KE', 'DJ'],
    'ZA': ['NA', 'BW', 'ZW', 'MZ', 'SZ', 'LS'],
    'KR': ['KP'],
    'SS': ['SD', 'ET', 'UG', 'CD', 'KE'],
    'ES': ['PT', 'FR', 'AD'],
    'LK': [],
    'SD': ['EG', 'LY', 'TD', 'CF', 'SS', 'ET'],
    'SR': ['VE', 'GY', 'BR'],
    'SE': ['NO', 'FI'],
    'CH': ['DE', 'FR', 'IT', 'AT'],
    'SY': ['TR', 'IQ', 'JO', 'IL', 'LB'],
    'TJ': ['AF', 'CN', 'KG', 'UZ'],
    'TH': ['MM', 'LA', 'KH', 'MY'],
    'TL': ['ID'],
    'TG': ['BF', 'GH', 'BJ'],
    'TO': [],
    'TT': [],
    'TN': ['DZ', 'LY'],
    'TR': ['BG', 'GR', 'GE', 'AM', 'AZ', 'IR', 'IQ', 'SY'],
    'TM': ['IR', 'AF', 'UZ', 'KZ'],
    'UG': ['KE', 'SS', 'CD', 'TZ', 'RW'],
    'UA': ['PL', 'SK', 'HU', 'RO', 'MD', 'RU', 'BY'],
    'AE': ['OM', 'SA'],
    'GB': ['IE'],
    'US': ['CA', 'MX'],
    'UY': ['AR', 'BR'],
    'UZ': ['KZ', 'TM', 'AF', 'TJ', 'KG'],
    'VU': [],
    'VE': ['CO', 'BR', 'GY'],
    'VN': ['CN', 'LA', 'KH'],
    'YE': ['SA', 'OM'],
    'ZM': ['CD', 'TZ', 'MW', 'ZW', 'NA', 'AO'],
    'ZW': ['ZA', 'BW', 'ZM', 'MZ']
};

function main() {
    const countryCodeInput = prompt("Enter a country code: ").toUpperCase();

    const countryName = getCountryName(countryCodeInput);

    if (countryName) {
        console.log(`You have entered: ${countryName}`);

        const adjacentCountries = getAdjacentCountries(countryCodeInput);
        if (adjacentCountries && adjacentCountries.length > 0) {
            console.log('Adjacent Countries are:');
            adjacentCountries.forEach(country => console.log(country));
        } else {
            console.log('No adjacent countries found.');
        }
    } else {
        console.log("Invalid country code entered. Please try again.");
    }
}

function getCountryName(countryCode: string): string | undefined {
    return countryCodes[countryCode];
}

function getAdjacentCountries(countryCode: string): string[] | undefined {
    const adjacentCodes = adjacentCountries[countryCode];
    if (!adjacentCodes) return undefined;

    return adjacentCodes.map((adjacentCountryCode: string) => countryCodes[adjacentCountryCode]).filter(Boolean);
}

main();